global using AllergenService.Grpc;
global using Carter;
global using FluentValidation;
global using Mapster;
global using Marten;
global using MediatR;
global using RecipeManager.Api.Entities;
global using RecipeManager.Api.Exceptions;
global using RecipeManager.Api.Services;
